### PR TITLE
Add Django 5.0 to test matrix (fixes #704)

### LINKED ISSUE #704: Add Django 5.x to test matrix
- Add Django 5.x to `nox` setup: https://github.com/adamghill/django-unicorn/blob/main/noxfile.py#L5
- Add Python 3.12 to https://github.com/adamghill/django-unicorn/blob/main/.github/workflows/python.yml#L9

### PR DESCRIPTION
**Pull request by JeremyLWright**
- timezone information is now on by default, and serilizers are expecting zulu time.
- Replace manual timestamp truncation with datetime timespec set to milliseconds

### CODE REVIEW

**Comment by JeremyLWright** [comment]
Django 5.0 is now supported on python 3.9 and 3.9, Do you have a recommend method to exclude 5.0 for those python version CI runs?

**Comment by adamghill** [comment]
>Do you have a recommended method to exclude 5.0 for those python version CI runs?

I don't think I've ever had to do this, but you might be able to check the Django version and Python version and skip the install/running the tests for the sessions that aren't supported?

**Comment by adamghill** [comment]
Oh, interesting. I wonder if `nox` is really needed anymore since everything is getting moved into GitHub actions at this point?

On the one hand, I liked being able to call `nox` locally, but I wonder if something like https://github.com/nektos/act would provide the same functionality?

Well, thanks for these changes I'll take a look at this more in depth soon and figure out what (if anything) I want to do about `nox` unless you have any thoughts about that.

**Comment by adamghill** [comment]
It looks like the actions error here: https://github.com/JeremyLWright/django-unicorn/actions/runs/10081907372/job/27874989875#step:6:12. I don't think `poetry add python==${{ matrix.python-version }}` can be used, but maybe `poetry env use ${{ matrix.python-version }}` would work?

**Comment by adamghill** [comment]
@JeremyLWright Removing support for Python 3.8 and 3.9 greatly reduces the complications: https://github.com/JeremyLWright/django-unicorn/commit/3c25dd37ae81a8a83814dd86eccb31143ed05f1d. Django 5.0 has dropped support for those versions, so it doesn't seem completely unreasonable. What do you think?

**Comment by adamghill** [comment]
@all-contributors add JeremyLWright code

**Comment by JeremyLWright** [comment]
> ed support for those versions, so it doesn't seem completely unreasonable.

It wasn't my call to make, @adamghill 😂. Dropping support does indeed make it easier.

**Pull request merged**
