### PR TITLE
Redirect from a component action method

### PR DESCRIPTION
**Pull request by adamghill**

### CODE REVIEW

**Comment by adamghill** [comment]
Inspired by https://github.com/adamghill/django-unicorn/discussions/97.

**Comment by frbor** [comment]
Hi,

I got this to work, but I had to change some code to check for redirect.url as well:

[https://github.com/adamghill/django-unicorn/compare/component-redirect...frbor:component-redirect](https://github.com/adamghill/django-unicorn/compare/component-redirect...frbor:component-redirect)

Without this change I was redirected to /.../undefined in some components, even when no redirect values were returned.

I'm not that familiar with javascript, but it looks like `{}` is a truthy value? 

However, I liked the generic change here where you can return other types in the future. I was looking into whether it is possible to "stop polling", and maybe the return logic can be reused there as well?

Nice work!

**Comment by adamghill** [comment]
Oh 🤦, yeah I need a better check for that redirect value. Thanks for pointing that out to me -- this is what I get for not testing thoroughly before making a PR! :)

My plan was to expose a `returnValue` or `lastReturnValue` or something that could be retrieved in Javascript, but I'm not quite sure how to expose it. Initially, I was thinking of something like `Unicorn.lastReturnValue('hello-world')` (similar to https://www.django-unicorn.com/documentation/components/actions#calling-methods), but I'm not sure how helpful that might be. Another option is create a special variable like `$returnValue` (similar to https://www.django-unicorn.com/documentation/components/actions#special-arguments). If you have thoughts about either, that would be useful.

Stopping polling is a good idea I hadn't thought of. Maybe something like `u:poll.stop=stopper` (where `stopper` could be a field, property, or method in the component) would be useful?

**Comment by frbor** [comment]
Unfortunately I do not have any good ideas regarding your question on the exposed `returnValue/lastReturnValue`.

To stop polling using `u:poll.stop=stopper` sounds like it will work out nicely.

The other option might be to use return values with a special Object on the component, that then needs to be checked like you do with redirect. So for instance:

Ship this simple class with django-unicorn:

```python
class UpdatePolling:
    def __init__(self, disable=False, refresh_time=None):
        self.disable = disable
        self.refresh_time = refresh_time
```

which then ca be used for both disabling polling and updating refresh_time:

```python
def save_book1(self):
    book = Book(title="Title)
    book.save()

    return UpdatePolling(disable=True)

def save_book2(self):
    book = Book(title="Title)
    book.save()

    return UpdatePolling(refresh_time=4000)
```

During testing I did find use of disabling polling, but others might find use for update the refresh_timer. However, the idea with `u:poll.stop=stopper` is somewhat easier so I might think that is just as good idea.

Sorry for cluttering this PR with the ideas on updating polling.

br, Fredrik

**Comment by adamghill** [comment]
>Sorry for cluttering this PR with the ideas on updating polling.

No worries! I ended up moving the "stop polling" request to https://github.com/adamghill/django-unicorn/issues/99, but I appreciate all of your thoughts. I'll try to figure out a simple API for this use-case, too.

**Pull request merged**
