### PR TITLE
Use AST.parse for call method parsing

### PR DESCRIPTION
**Pull request by adamghill**

### CODE REVIEW

**Comment by adamghill** [comment]
Based on #146 by @frbor with some extra tests and initial support for #13. Also would close #87 and #71! In testing it looks solid, but I want to look into `ast.parse` for the `parse_kwarg` method and add more tests over the next day or two.

I'm planning on packaging it up as 0.19.0 because it is sort of a substantial change.

**Comment by adamghill** [comment]
@all-contributors add @frbor for code and test

**Comment by frbor** [comment]
I did look into replacing parse_kwarg as well on my first PR, but gave up, since it failed to many tests, and there were unrelated things I did not know about :)

However, here is a first shot, which might a usable starting point:

```python
def parse_kwarg(kwarg: str, raise_if_unparseable=False) -> Dict[str, Any]:

    try:
        tree = ast.parse(kwarg, "eval")
    except SyntaxError:
        if raise_if_unparseable:
            raise InvalidKwarg

    if tree.body and isinstance(tree.body[0],ast.Assign):
        assign = tree.body[0]
        return {assign.targets[0].id: ast.literal_eval(assign.value)}

    else:
        raise InvalidKwarg

print(parse_kwarg("test='1'"))
print(parse_kwarg("test=1"))
```

outputs:
```
{'test': '1'}
{'test': 1}
```

**Comment by adamghill** [comment]
@frbor I incorporated https://github.com/adamghill/django-unicorn/pull/149#issuecomment-772283695 into this PR, but to deal with accessing nested properties (i.e. `this.is.nested` is valid to get to `{"this":{"is":{"nested":True}}}` I had to deal with `Attribute` and `Name` expressions. I think I handle it ok, but maybe you know of a cleaner way than https://github.com/adamghill/django-unicorn/pull/149/files#diff-28a2ce5d81ceb5b67d75f74459011aef36efbdbfae728316669de642b2033e8aR31?

I'd love any other feedback on the current state of this PR when you have the time. I've added a bunch of new tests and have stress-tested it as much as possible, so I think it's good to ship if you think so as well.

**Comment by frbor** [comment]
@adamghill I'm thrilled that you took the ideas and got it working with kwargs!

I tried looking at a recursive alternative to `_get_expr_string` but did not get it to work, but anyhow I do think that the current solution might be more readable.

So this looks really good to me!

**Comment by frbor** [comment]
Got the chance to look into an alternative solution. This passes the test, but I'm stil not sure if is more readable..

```python
def _get_expr_string(expr: ast.expr, expr_str: str = "") -> str:
    """
    Builds a string based on traversing `ast.Attribute` and `ast.Name` expressions.

    Args:
        expr: Expression node of the the AST tree. Only handles `ast.Attribute` and `ast.Name` expressions.

    Returns:
        String based on the expression nodes.
    """

    if isinstance(expr, ast.Name):
        return f"{expr.id}.{expr_str}" if expr_str else expr.id
    elif isinstance(expr, ast.Attribute):
        expr_str = f"{expr.attr}.{expr_str}" if expr_str else expr.attr
        return _get_expr_string(expr.value) + "." + expr_str
    else:
        return expr_str

```

**Comment by adamghill** [comment]
Thanks! I played with your recursive solution a little bit. I could go either way, but personally I find the while loop a little easier to reason about. 🤷‍♂️ My original approach was recursive, too (it definitely _seems_ like the right way to solve it), but it's not really a tree, so the loop seems good enough.

**Comment by adamghill** [comment]
Released in 0.19.0. 🎉

**Comment by frbor** [comment]
Yes, I do agree that the loop was actually easier to grasp!

Thanks for including this in 0.19.0. I have tested it and everything works as expected for me now!

**Pull request merged**
