### PR TITLE
Update client-side components from server responses

### PR DESCRIPTION
**Pull request by imankulov**
- Annotate root elements for Unicorn components with unicorn:data attributes.
- Post-process Unicorn responses: delete Component objects for nodes that were
  removed from the DOM, and add new Component instances for newly created nodes.

Ref: #530

### CODE REVIEW

**Comment by adamghill** [comment]
This is an interesting approach! Does it make `initjs` data redundant if it's all attributes on the component itself? Would [calls](https://github.com/adamghill/django-unicorn/pull/600/files#diff-3be036be1967d2fe826c843d99aa27449ad1ed0d592f5e3fe242203a8cf36a2fR64) be able to be stored as an attribute as well?

At first glance having this data sitting in the HTML of the element feels like we are mixing separation of concerns, but I'm not sure it actually matters (?) and it does seem like it will be easier to keep the component state up to date.

**Comment by imankulov** [comment]
Yes, this is redundant. In its current form, we are passing the same attributes twice. Additionally, we are initializing components in two different ways:

```
Unicorn.componentInit(...);
Unicorn.componentInit(...);
...
```

and then:

```javascript
findUnicorns().forEach((el) => {  
	Unicorn.insertComponentFromDom(el);  
});
```

I feel like calling `findUnicorns() -> insertComponentFromDom()` can also work to initialize components on the first load, but I haven't experimented with it.

As for mixing separation of concerns, I don't have a strong opinion on this. Putting JSON in HTML attributes is likely weird, but [not as weird as putting JavaScript in attributes](https://alpinejs.dev/directives/data), like some others do.

> Would [calls](https://github.com/adamghill/django-unicorn/pull/600/files#diff-3be036be1967d2fe826c843d99aa27449ad1ed0d592f5e3fe242203a8cf36a2fR64) be able to be stored as an attribute as well?

Yes! I added a commit that does that.

**Comment by adamghill** [comment]
>I feel like calling findUnicorns() -> insertComponentFromDom() can also work to initialize components on the first load, but I haven't experimented with it.

That was what I was wondering. Looking at the code, I would _think_ it would work fine, but I've been wrong before when I assume I understand how code works in the past. 😆 

This seems like a more sustainable approach than what is currently implemented _and_ solves some gnarly bugs with nested components. What do you need from me to push this PR forward? Is it just stress testing and making sure the implementation seems sound?

**Comment by imankulov** [comment]
> What do you need from me to push this PR forward? Is it just stress testing and making sure the implementation seems sound?

Yes, I would appreciate it if you could look in depth at this code to see if it works well and covers all corner cases. I am still fairly new to Unicorn, and I might overlook some issues with existing functionality that I didn't take into account.

Then, to avoid scope creep, maybe we could have a follow-up issue if we want to replace a series of `Unicorn.componentInit(...);` with `Unicorn.insertComponentFromDom()`.

**Comment by imankulov** [comment]
@adamghill, I have rebased this PR on top of the latest "main" branch and resolved the conflicts. Do you think we can proceed with making it mergeable? If so, what would you expect from me here? Thanks!

**Comment by adamghill** [comment]
Thanks for rebasing! Yep, this is next on my list to look at it. 😄 I will start looking at it this week, but I need to dedicate a few hours to making sure this is stable before merging. 👍

**Comment by adamghill** [comment]
I added an example that would fail previously, but works with this PR. I can understand the code and it appears to work to solve #530. One thing I'm personally not thrilled about is the `unicorn:data` attribute in the HTML attribute. I do realize this is pretty subjective, though.

Could the current `script` tag used with the initial JSON be used/updated instead? It would feel cleaner to me. The downside is that it's separated from the component HTML.

Or another option would be to base64 encode the `unicorn:data` HTML attribute?

Or should I not worry about this at all? 😆

**Comment by adamghill** [comment]
I added:
- more to the wizard example
- removed data keys from being included in the payload if it wasn't used by a unicorn:model (not sure how this interacts with `javascript_exclude`
- `$parent` special variable for the template
- tweaked the morphdom options to hopefully diff better

I might cherrypick some of these fixes and features into `main` before merging this branch in, but I haven't decided for sure yet. And everything needs some tests to be added before merging in.

**Comment by adamghill** [comment]
This got merged in 0.58.0, thank you for this approach and all your thoughts on improving Unicorn!

**Pull request closed without merging**
