### PR TITLE
Re-fire poll method when tab is refocused

### PR DESCRIPTION
**Pull request by adamghill**

### CODE REVIEW

**Comment by frbor** [comment]
Thanks for looking into this feature!

This should cover my use case, and it might be that I have missed something here, but isn't the `fireImmediately` argument redundant here, as it is always true where we call `startPolling`?

If I'm correct, i suggest to remove this argument or make `fireImmediately` configurable.

If I have misunderstood something, please go ahead and merge :)

**Comment by adamghill** [comment]
I added the `fireImmediately` argument because `startPolling` also gets called when the component request comes back and there is a `PollUpdate` in the view: https://github.com/adamghill/django-unicorn/blob/master/django_unicorn/static/js/messageSender.js#L143.

**Comment by frbor** [comment]
I see, then this looks good to me.

**Comment by adamghill** [comment]
@frbor This fix is now out deployed in 0.28.0. Thanks for the original PR! 🎉

**Pull request merged**
