### PR TITLE
Model, example and fixtures for testing #189

### PR DESCRIPTION
**Pull request by mbacicc**
I applied part of my model, i created a component named model-relations to test it, I inserted the component together with the other examples:
with commit fc7bfd08cd05adf0726088a08775ec8fec5a832c (I suppose 0.27.1):
- Applying electronics/fixtures/foreignkey/single_board_without_status.json - WORKS
- Applying electronics/fixtures/foreignkey/single_board_with_unlinked_status.json - WORKS
- Applying electronics/fixtures/foreignkey/single_board_with_linked_status.json - AttributeError: 'Board_Status' object has no attribute 'name'
-  Both m2m fixtures work properly.
With this PR works also with electronics/fixtures/foreignkey/single_board_with_linked_status.json

### CODE REVIEW

**Comment by adamghill** [comment]
Thanks for going to all this trouble with this PR! I ran `loaddata` on single_board_without_status.json, single_board_with_unlinked_status.json, and single_board_with_linked_status.json. But, it seems like I am able to save updates? See the gif below:

Apr-24-2021 19-43-10

When do you see the `AttributeError` thrown?

**Comment by mbacicc** [comment]
It's really strange, on what commit you tried this?
I tried it again:

- started from e398875d352065c8bff084b57dd9523d1046508d (the first in this PR)
- empty db (deleted the db.sqlite3 file to be sure to start from the same starting point)
- migrate
- createsuperuser
- logged in admin console (otherwise my component can't assign last edit user)
- loaddata electronics\fixtures\foreignkey\single_board_with_linked_status.json (I'm on windows)

Now, Even without assigning a new status, already the process of saving the model instance connects the board last edited by field to the request user and it triggers the error in this way:

- I go on my example page Model-relations
- I click Edit, everything ok (no foreign key connected to any field of Arduino board)
- I click Save, everything ok, but the component linked me (logged in user to board last edit by)
- i click Edit, and I obtain: AttributeError: 'User' object has no attribute 'name'

Let me know what other context info I can provide you to better understand what is happening.

**Comment by adamghill** [comment]
Your video was super useful for me to see how to replicate, thanks! I see the issue now and am trying to figure out what the best solution is.

**Comment by adamghill** [comment]
I just pushed https://github.com/adamghill/django-unicorn/commit/4a3d4c769a0acc4015d9bcba06f5e11cc9762dbc to master. Can you check if that fixes the bug? From what I can tell, that code isn't needed for anything so I removed it completely.

**Comment by mbacicc** [comment]
I merged your commit on just after e398875d352065c8bff084b57dd9523d1046508d and it seems working properly.
Just to be sure I also tried it with M2M relation:
image
I think you can safely close this PR, discarding its content, it's a duplicate of your example, not adding anything extremely useful. 
Maybe you can add a foreignkey to coffee example from flavor to user for instance? 
I removed the video link, not useful anymore.

Thank you!

**Comment by adamghill** [comment]
Closing this, but thanks again for the detailed PR. It was very helpful so I could figure out what was going on. 👍

**Pull request closed without merging**
