### PR TITLE
Warn if there is a missing parent element

### PR DESCRIPTION
**Pull request by adamghill**
Log a message if:
- there isn't a "wrapper" element (i.e. the component has more than 1 root element)
```html
<!-- component-one.html -->
<input unicorn:model="first_name"></input>
<input unicorn:model="last_name"></input>
```
- the root element doesn't have children
```html
<!-- component-two.html -->
<input unicorn:model="first_name"></input>
```

I should also update the docs to make it more clear, but a "wrapper" element is required for the DOM diffing algorithm to work properly. These checks should hopefully help catch invalid component templates earlier.

### CODE REVIEW

**Comment by adamghill** [comment]
@cyface How does this more explicit warning in the documentation with examples look?

image

**Comment by adamghill** [comment]
Yeah, I think something like that could work. I'll continue to ruminate.

**Comment by rhymiz** [comment]
this is super helpful

**Comment by adamghill** [comment]
After re-reading the docs a few times, I realized that it doesn't explicitly make it clear that components are a Python view + HTML template. So, I explicitly split out a new `views` page and re-arranged a lot of the content. The overall goal is to reduce the head scratching moments that new users run into and generally clarify the concepts behind `Unicorn`.

**Comment by kevinbowen777** [comment]
line 154 in `docs/source/views.md`:

I noticed that you went to the effort of removing a "just" statement in `templates.md`. It might be worthwhile to do so here as well:

"Inheriting from `unicorn.components.UnicornField` is a quick way to serialize a custom class as it calls `self.__dict__` under the hood."

**Comment by adamghill** [comment]
> I noticed that you went to the effort of removing a "just" statement in `templates.md`. It might be worthwhile to do so here as well

Thanks for pointing that out @kevinbowen777. I've been trying to remove words like "just", "simple", "quick", etc. although I'm sure they are still more in there. 😄 

I also just pushed some more changes mostly around rearranging the sidebar navigation to (hopefully) make things more clear.

**Comment by cyface** [comment]
Typo in early part of the docs “forcing you to *re-building* your application”

**Comment by adamghill** [comment]
>Typo in early part of the docs

Thanks! 🚀

**Comment by adamghill** [comment]
I'm going to merge this in, but any other feedback on doc changes would still be appreciated. 👍

**Pull request merged**
