### PR TITLE
Update `startunicorn` command to prevent spamming

### PR DESCRIPTION
**Pull request by felipmartins**
Greetings @adamghill !

I was following documentation and noticed that creating multiple components for the first time in an app results in an undesired loop (print below)

Captura de Tela 2023-12-05 às 19 37 30

The changes I'm proposing fix that by checking the number of files in components folder. (print below)

Captura de Tela 2023-12-05 às 19 34 47

Let me know if you need anything!

### CODE REVIEW

**Comment by adamghill** [comment]
Hey, sorry I missed this -- thanks for the PR! This looks like it would fix the problem, but would it be cleaner to set `is_first_component` to `False` on line 196?

**Comment by felipmartins** [comment]
You are absolutely right, @adamghill . I made the change following your suggestion, much cleaner!

But anyway, someday it might make sense to extract some logic from this loop. I mean, does not please me the idea of having such an extensive loop containing all logic.

Makes sense?

**Comment by adamghill** [comment]
>someday it might make sense to extract some logic from this loop

Yep, makes sense to me! I'd merge a PR if you want to extract that logic.

**Comment by felipmartins** [comment]
@adamghill, sorry for taking so long to reply this.

You can close this PR, I've just [sent another one](https://github.com/adamghill/django-unicorn/pull/642)

**Comment by adamghill** [comment]
No worries, I know how it is! 😆

**Pull request closed without merging**
