### PR TITLE
Partial fix for nested child components updates bug

### PR DESCRIPTION
**Pull request by gschurck**
Partial fix proposal for #530.

As [I explained](https://github.com/adamghill/django-unicorn/issues/530#issuecomment-1570639581) in the issue, the bug seems to be linked to the fact that script tags where not updated for each child components displayed after the first page load. Resulting in children being ignored and no actions could work on it.

With this fix, actions worked for me.
But to test it I had to set children components `data` field manually on client side according to their state on server, because I don't know how to get the data field efficiently for each new child. We need it to validate the checksum and send a request to the server.

### CODE REVIEW

**Comment by hendi** [comment]
Let's try to get this in a mergeable state :bowing_man: 

@adamghill can you please elaborate on "how to get the data field efficiently for each new child"?

**Comment by adamghill** [comment]
Yep, so what @gschurck is saying is this fix would require the code to look at every DOM element node on the page every time a new AJAX call is received. I need to test the performance implications of this and I'd also like to figure out if maybe there is a simpler and/or more straight-forward approach. I'll let you know what I come up with.

**Comment by hendi** [comment]
@imankulov this is a fundamental feature, please check with @adamghill

**Comment by adamghill** [comment]
I think this should be fixed by 0.58.0 of `Unicorn` which drastically improves child components so I'm going to close this PR. If it is still a problem feel free to re-open a new issue. Thank you!

**Pull request closed without merging**
