### PR TITLE
adding the scroll attribute to call a function when window scroll is …

### PR DESCRIPTION
**Pull request by MayasMess**
…at the bottom

I didn't find a way to implement an infinite scroller with the visibility attribute because it only call the fonction one time and then the element is set to visible. 
I added this scroll attribute and it seems to work well. I don't know if the simple name "scroll" is explicit enough ^^'

This is my first "try/contribution" to an open source project so please tell me if there is something missing ^^

### CODE REVIEW

**Comment by adamghill** [comment]
Hey @MayasMess this is awesome! I have a few thoughts:
- it sounds like `unicorn:visible` wasn't re-firing after the first time it became visible? I'm surprised this was happening because the `IntersectionObserver` that is used under the hood _should_ fire again when the element is seen again. I'll try to make an example to replicate that functionality.
- I'm not opposed to `visible:scroll`, but I do wonder how different it is from `unicorn:visible`? Does it achieve the same goal? Is it confusing to have both?

In terms of other things to add to the PR before it gets merged, I tend to add an example to the sample site so I can check it end-to-end and a test or two as need. For this it would only be a JavaScript test which uses `ava`.

**Comment by adamghill** [comment]
I just added an example for using `unicorn:visbile` for infinite scrolling in 5b28268. It looks like this for me:
visible-infinite-scroll

But, still not opposed to something like `unicorn:scroll`, I just want to make sure I understand the use-case. 👍

**Comment by MayasMess** [comment]
I tested the example you added and yeah it's working ! but I still can't find why my todo list example doesn't work x) https://github.com/MayasMess/testing-django-unicorn

For the scroll attribut it's not needed anymore I think, because the visibility attribut can do the same things and more.
I'll continue to investigate why in my case it didn't work and add a coms if I find something ^^

Thanks @adamghill

**Comment by adamghill** [comment]
I've been using your test example to see what is going on and I can replicate the issue. I'm still trying to figure out how to fix the issue, though. I'll let you know when I come up with something!

**Comment by adamghill** [comment]
Woohoo! Looks like I might have a fix working with your test repo. I'm going to test some more, but hopefully can get a patch release out tomorrow to get this working for you.

**Comment by adamghill** [comment]
There is a fix in 7fa885b8423f4772766649b042c45bf77fc8b54b which will got released in 0.35.2. Gonna close this for now, but let me know if you run into any other issues.

**Comment by adamghill** [comment]
@all-contributors add @MayasMess for code

**Comment by riquedev** [comment]
> I just added an example for using `unicorn:visbile` for infinite scrolling in [5b28268](https://github.com/adamghill/django-unicorn/commit/5b282681cd93c19fb095429ab6674e05d3cbcb95). It looks like this for me: visible-infinite-scroll
> 
> But, still not opposed to something like `unicorn:scroll`, I just want to make sure I understand the use-case. 👍

Hey, why not add to the site examples?
This is really cool!

https://www.django-unicorn.com/examples/todo

**Pull request closed without merging**
