### PR TITLE
Delete extra_context

### PR DESCRIPTION
**Pull request by towan912**
`extra_context` was overwriting parent component's view. #411

### CODE REVIEW

**Comment by adamghill** [comment]
Thanks for this PR. I'm trying to replicate the problem in my example of [nested components](https://github.com/adamghill/django-unicorn/blob/main/example/unicorn/components/nested/table.py), but I do not see a difference between `main` and this PR. Can you add an example to replicate the problem and some tests to verify this works as expected? Thanks!

**Comment by towan912** [comment]
I rebased the branch for add issues example.
Checkout 645cff3 and open this [page](http://localhost:8000/class-view), you can see replicate the problem.

This PR is my first time contribution, so may annoy you some time.
Thanks.

**Comment by adamghill** [comment]
No annoyance, I appreciate all PRs! I did spend some time recently on nested components and released it in 0.46.0. Can you check that out and see if it works as you expected? Thanks again! I'm going to close this for now, but let me know if you still are running into problems.

**Comment by towan912** [comment]
I will be later check works as expect released 0.46.0.
Thanks for fix!

**Pull request closed without merging**
