### PR TITLE
update get_locations

### LINKED ISSUE #654: handling non-standard django app configs
This is a bug that I have a working fix for. I will open an PR shortly for @adamghill to review 😃 

## Summary of bug

The utility at `components.unicorn_view.get_locations` incorrectly assumes the python path for django apps follows the format of `path.to.apps.ExampleConfig`. This is not always the case because some django teams choose to store configs elsewhere. 

## Example

Here are some example configs where the bug exists: https://github.com/jacksund/simmate/blob/main/src/simmate/apps/configs.py

You'll see the configs are located at `simmate.apps.configs` *and* each config points to a different location for where the django app lives. Thus, unicorn is crashing because it incorrectly handles the a string such as `simmate.apps.configs.WarrenLabConfig` that is in `INSTALLED_APPS`.

## Suggested fix

This issue can be fixed by using django's official recommendations on how to interact with configs:

- django cautions against interacting with `INSTALLED_APPS`, but instead recommends loading configs via `django.apps.apps` ([source](https://docs.djangoproject.com/en/5.0/ref/settings/#installed-apps))
- the `get_locations` is really after the python import path for the app. This is stored as `name` on the app's config object ([source](https://docs.djangoproject.com/en/5.0/ref/applications/#django.apps.AppConfig.name))

## Implementing the fix

The following code will be replaced:
https://github.com/adamghill/django-unicorn/blob/7097b6315ff96e399719c1dee028bcab2ca33988/django_unicorn/components/unicorn_view.py#L109-L137

The new implementation will be as follows:
``` python
from django.apps import apps as django_apps

# note: app_config.name gives the python path
all_django_apps = [app_config.name for app_config in django_apps.get_app_configs()]
unicorn_apps = get_setting("APPS", all_django_apps)

if not is_non_string_sequence(unicorn_apps):
    raise AssertionError("APPS is expected to be a list, tuple or set")

locations += [(f"{app}.components.{module_name}", class_name) for app in unicorn_apps]
return locations
```

### PR DESCRIPTION
**Pull request by jacksund**
closes #654

### CODE REVIEW

**Comment by jacksund** [comment]
@adamghill this is ready for review. It works in my local setup but I'm not sure if there's are CI/unittests that you can run on it as well

**Comment by jacksund** [comment]
also (if you accept this PR) would you be willing to do a patch release for it?

**Comment by adamghill** [comment]
>would you be willing to do a patch release for it?

I would include it in the next minor version most likely. Would that work for you?

**Comment by jacksund** [comment]
> Would that work for you?

As long as the next minor release isn't several months away, that'd be perfect haha. Thank you 😄

**Comment by adamghill** [comment]
@all-contributors please add @jacksund for code

**Comment by adamghill** [comment]
>As long as the next minor release isn't several months away

🎉 0.59.0 with your fix is now on [PyPI](https://pypi.org/project/django-unicorn/). 🎉

**Comment by jacksund** [comment]
oh woah! Thanks for doing that so quickly 🚀

**Pull request merged**
